name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:

  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: echo "Hello World"
