name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: python3/home/st22122104/projects/odoo/server14/odoo-bin -c /home/st22122104/projects/odoo/config/odoo14_new.conf 
