# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

        
      - name: Test
        run: source /home/st22122104/projects/odoo15/odoo15venv/bin/activate
      
      - name: Requirement
        run: pip install greenlet
      
      - name: Requiremen
        run: echo $(python <<EOF
              import sys
              if sys.prefix == sys.base_prefix:
                  print("No, you are not in a virtual environment.")
              else:
                   print("Yes, you are in a virtual environment.")
              EOF
              )
        
      - name: Requireme
        run: pip install --upgrade setuptools
      - name: Requirements
        run: pip install -r requirements.txt
        
      - name: Odoo
        run: python3.9 /home/st22122104/projects/odoo15/odoo/odoo-bin -c /home/st22122104/projects/odoo15/config/odoo15.conf
