# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        
      - name: Test
        run: source /home/st22122104/projects/odoo9TS/odoo_IT/bin/activate
    
      - name: ODOO
        run: python2.7 /home/st22122104/projects/odoo9TS/odoo-9-ce-bundle/source/openerp-server -c /home/st22122104/projects/odoo9TS/conf/odoov9_CE_OIT.conf
