# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

        
      - name: Test
        run: source /home/st22122104/projects/odoo15/venv/bin/activate
        
      - name: Install dependencies
        run: pip install Pillow=9.1.1
    
      - name: ODOO
        run: python3.8 /home/st22122104/projects/odoo15/odoo/odoo-bin -c /home/st22122104/projects/odoo15/config/odoo15.conf
